services:
  - type: web
    name: docubot-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: YANDEX_FOLDER_ID
        value: b1gdcuaq0il54iojm93b
      - key: PORT
        value: 10000